### ISSUE TITLE
Apontamentos Pedro 20/03

### ISSUE THREAD

**Issue by pedroida** [aleraymann/Desafio-Lets#3]
Quando edito um produto, não puxa a descrição dele e quando salvo a edição, não salva a imagem nova.

Trate os campos que não podem ser nulos, por exemplo, tentei criar um pruduto sem descrição, da erro.

Quando apagar um produto, apagar sua imagem do storage também.

============= código ============
newProducts.blade.php => value="{{ old('descriprion') }} nome da chave incorreto, nao funciona.

editProducts.blade.php => está chamando a variável do produto a ser editado, um único, de $products, no plural

O que é o model Data?

Nome de classe sempre em camelCase. Exemplo: UserController, ProductController.

tem controllers com snake_case sobrando. Se não usa, apague.

dd() comentado no ProductController

'price'=> "required", "float",    Esse float deve ser depois do "required" dentra da string. "required|float". Do modo que está, ele está testando se vem uma chave com o nome "float".

**Comment by aleraymann** [comment]
Edição de produtos Ok
Campos nulos Ok
Apagar Img da Storage OK
Variavel $products em editView alterada para $product
model Data excluido
dd() no ProductController apagado

valew brow
required corrigido

**Comment by aleraymann** [comment]
Edição de produtos Ok
Campos nulos Ok
Apagar Img da Storage OK
Variavel $products em editView alterada para $product
model Data excluido
dd() no ProductController apagado
required corrigido

Valew Brow
